package expo.modules.youtubeextractor

import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.VideoStream

class YoutubeExtractorModule : Module() {
    override fun definition() = ModuleDefinition {
        Name("YoutubeExtractor")

        AsyncFunction("resolveAudioStream") { videoId: String ->
            ensureInitialized()

            val info = StreamInfo.getInfo("https://www.youtube.com/watch?v=$videoId")
            val source = pickAudioSource(info.audioStreams, info.videoStreams)

            mapOf(
                "url" to source.url,
                "mimeType" to source.mimeType,
                "title" to "${info.name}.${source.extension}",
                // YouTube's CDN can silently stall/timeout a plain request to a
                // resolved stream url - the download step needs to send the same
                // User-Agent (and a Referer) that resolved it.
                "userAgent" to USER_AGENT,
                "referer" to "https://www.youtube.com/",
            )
        }

        AsyncFunction("downloadAudioStream") { url: String, headers: Map<String, String>, destinationPath: String ->
            downloadInChunks(url, headers, destinationPath)
        }

        // Video (not muxed-for-audio) source, for the OCR-on-burned-in-captions
        // pipeline (see Drive Log 2026-08-26/09-01) - that path needs actual
        // frames, which resolveAudioStream's audio-only/smallest-muxed choice
        // doesn't reliably provide. Kept separate from resolveAudioStream so
        // the audio-only pipeline's download size is unaffected when OCR
        // isn't invoked.
        AsyncFunction("resolveVideoStream") { videoId: String ->
            ensureInitialized()

            val info = StreamInfo.getInfo("https://www.youtube.com/watch?v=$videoId")
            val source = pickVideoSource(info.videoOnlyStreams, info.videoStreams)

            mapOf(
                "url" to source.url,
                "mimeType" to source.mimeType,
                "title" to "${info.name}.${source.extension}",
                "userAgent" to USER_AGENT,
                "referer" to "https://www.youtube.com/",
            )
        }

        // Existing caption tracks, for the "use a finished transcript when
        // one exists, skip audio download/whisper entirely" fast path
        // reinstated in Drive Log 2026-09-01/02. Only original-language
        // tracks (creator-uploaded or YouTube's own speech-recognition
        // track) are returned here - NewPipeExtractor's default subtitle
        // list does not include YouTube's machine-translated variants,
        // which would violate the "never translate, preserve spoken
        // language" constraint.
        AsyncFunction("resolveSubtitles") { videoId: String ->
            ensureInitialized()

            val info = StreamInfo.getInfo("https://www.youtube.com/watch?v=$videoId")
            val tracks = info.subtitles.mapNotNull { subtitle ->
                val url = subtitle.content
                if (url.isNullOrEmpty()) return@mapNotNull null
                mapOf(
                    "url" to url,
                    "languageCode" to (subtitle.languageTag ?: ""),
                    "isAutoGenerated" to subtitle.isAutoGenerated,
                    "format" to (subtitle.format?.suffix ?: ""),
                )
            }

            mapOf("title" to info.name, "tracks" to tracks)
        }
    }

    private data class AudioSource(val url: String, val mimeType: String, val extension: String)
    private data class VideoSource(val url: String, val mimeType: String, val extension: String)

    // Picks a video source good enough for OCR-legible frames without
    // downloading a full-resolution file: closest to 480p, preferring the
    // audio-less DASH streams (smaller, and OCR never needs the audio track)
    // over muxed ones.
    private fun pickVideoSource(
        videoOnlyStreams: List<VideoStream>,
        muxedVideoStreams: List<VideoStream>,
    ): VideoSource {
        fun resolutionHeight(stream: VideoStream): Int =
            Regex("""\d+""").find(stream.resolution ?: "")?.value?.toIntOrNull() ?: Int.MAX_VALUE

        fun pick(streams: List<VideoStream>): VideoStream? =
            streams.filter { !it.content.isNullOrEmpty() }
                .minByOrNull { kotlin.math.abs(resolutionHeight(it) - 480) }

        val chosen = pick(videoOnlyStreams) ?: pick(muxedVideoStreams)
            ?: throw IllegalStateException("Could not find a downloadable video stream for this video.")

        val url = chosen.content!!
        val isWebm = chosen.format?.name?.contains("WEBM", ignoreCase = true) == true
        return if (isWebm) {
            VideoSource(url, "video/webm", "webm")
        } else {
            VideoSource(url, "video/mp4", "mp4")
        }
    }

    private fun pickAudioSource(
        audioStreams: List<AudioStream>,
        muxedVideoStreams: List<VideoStream>,
    ): AudioSource {
        if (audioStreams.isNotEmpty()) {
            // Prefer M4A/AAC over WebM/Opus - matches the existing preference
            // in sources.ts's WebView WAV-converter step, which needs a
            // format iOS/Android WebViews both reliably decode.
            val preferred = audioStreams.firstOrNull {
                it.format?.name?.contains("M4A", ignoreCase = true) == true
            } ?: audioStreams.maxByOrNull { it.averageBitrate } ?: audioStreams[0]
            val url = preferred.content
                ?: throw IllegalStateException("Found an audio stream with no downloadable url.")
            val isM4a = preferred.format?.name?.contains("M4A", ignoreCase = true) == true
            return if (isM4a) {
                AudioSource(url, "audio/mp4", "m4a")
            } else {
                AudioSource(url, "audio/webm", "webm")
            }
        }

        // Some videos expose no audio-only adaptive stream at all - fall back
        // to the smallest muxed video+audio stream rather than failing
        // outright. Only the audio track is needed, so pick the lowest
        // resolution to keep the download small.
        if (muxedVideoStreams.isNotEmpty()) {
            val smallest = muxedVideoStreams.minByOrNull { it.height } ?: muxedVideoStreams[0]
            val url = smallest.content
                ?: throw IllegalStateException("Found a video stream with no downloadable url.")
            return AudioSource(url, "video/mp4", "mp4")
        }

        throw IllegalStateException("Could not find a downloadable audio stream for this video.")
    }

    @Synchronized
    private fun ensureInitialized() {
        if (!initialized) {
            NewPipe.init(OkHttpDownloader())
            initialized = true
        }
    }

    companion object {
        @Volatile
        private var initialized = false
    }
}
