import { File, Paths } from 'expo-file-system';
import { resolveSubtitles, downloadStream, SubtitleTrack } from '../modules/youtube-extractor/src';

// Fast path: use an existing caption track directly when one is usable,
// instead of always downloading audio and running on-device whisper (Drive
// Log 2026-09-01/02, "Reinstating Captions as First-Try Fast Path" +
// corrections). Whisper's own real-world failure rate on this device
// (repetition loops, hallucination) has repeatedly been worse than an
// imperfect but available auto-caption, so this is tried first, not as a
// replacement for the audio pipeline (which remains the fallback).
//
// "Usable" means: a real caption track exists, in the video's own spoken
// language (not a machine-translated one - NewPipeExtractor's resolveSubtitles
// only returns original/ASR tracks to begin with, see its own comment), and
// the resulting deduplicated text is long enough to be real content rather
// than a broken/placeholder track.

const MIN_USABLE_LENGTH = 40;

function pickTrack(tracks: SubtitleTrack[], languageHint: string | null): SubtitleTrack | null {
  if (tracks.length === 0) return null;

  const matching = languageHint
    ? tracks.filter((t) => t.languageCode.toLowerCase().startsWith(languageHint.toLowerCase()))
    : tracks;
  const pool = matching.length > 0 ? matching : tracks;

  // Prefer a creator-uploaded track over YouTube's own auto-generated ASR
  // track - real captions are typically cleaner and won't have the
  // rolling-overlap artifact auto-generated ones have.
  return pool.find((t) => !t.isAutoGenerated) ?? pool[0];
}

// Strips WebVTT/TTML markup tags (styling, inline word-timing tags common in
// YouTube's auto-generated cues, XML elements) - only the visible cue text
// is kept.
function stripTags(text: string): string {
  return text.replace(/<[^>]*>/g, '');
}

// YouTube's caption data is HTML-escaped - decode it back to real characters
// (Drive Log 2026-09-01: "you&#39;re" was showing up literally instead of
// "you're"). Handles named entities, decimal (&#39;), and hex (&#x27;)
// numeric entities generically, not just the apostrophe case that was seen.
const NAMED_ENTITIES: Record<string, string> = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
  nbsp: ' ',
};

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)))
    .replace(/&([a-zA-Z]+);/g, (match, name) => NAMED_ENTITIES[name.toLowerCase()] ?? match);
}

function parseWebVtt(content: string): string[] {
  const blocks = content.replace(/\r/g, '').split(/\n\n+/);
  const cues: string[] = [];
  for (const block of blocks) {
    const lines = block.split('\n').filter(Boolean);
    const timingIndex = lines.findIndex((l) => l.includes('-->'));
    if (timingIndex === -1) continue;
    const text = lines
      .slice(timingIndex + 1)
      .map(stripTags)
      .join(' ')
      .trim();
    if (text) cues.push(text);
  }
  return cues;
}

function parseTtml(content: string): string[] {
  const matches = content.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/gi);
  const cues: string[] = [];
  for (const match of matches) {
    const text = stripTags(match[1]).replace(/\s+/g, ' ').trim();
    if (text) cues.push(text);
  }
  return cues;
}

// Auto-generated cues typically "roll" - each new cue repeats the tail of
// the previous one and appends new words (a live-captioning artifact), so a
// naive join produces heavily duplicated text (Drive Log 2026-09-01,
// "Correction - Finished Transcript Means YouTube's Transcript Panel").
// Detect the actual word-level overlap between consecutive cues and only
// append the genuinely new part.
function mergeCues(cues: string[]): string {
  let result = '';
  let resultWords: string[] = [];

  for (const cue of cues) {
    const cueWords = cue.split(/\s+/).filter(Boolean);
    if (resultWords.length === 0) {
      result = cue;
      resultWords = cueWords;
      continue;
    }

    const maxOverlap = Math.min(resultWords.length, cueWords.length, 20);
    let overlapLength = 0;
    for (let len = maxOverlap; len > 0; len--) {
      const tail = resultWords.slice(-len).join(' ').toLowerCase();
      const head = cueWords.slice(0, len).join(' ').toLowerCase();
      if (tail === head) {
        overlapLength = len;
        break;
      }
    }

    const newWords = cueWords.slice(overlapLength);
    if (newWords.length === 0) continue;
    result += (result ? ' ' : '') + newWords.join(' ');
    resultWords = resultWords.concat(newWords);
  }

  return result;
}

export type CaptionsOutcome =
  | { status: 'found'; text: string; title: string }
  | { status: 'unavailable' };

export async function tryFetchCaptions(
  videoId: string,
  languageHint: string | null
): Promise<CaptionsOutcome> {
  let title: string;
  let tracks: SubtitleTrack[];
  try {
    const resolved = await resolveSubtitles(videoId);
    title = resolved.title;
    tracks = resolved.tracks;
  } catch {
    return { status: 'unavailable' };
  }

  const track = pickTrack(tracks, languageHint);
  if (!track) return { status: 'unavailable' };

  const destination = new File(Paths.cache, `captions-${videoId}-${Date.now()}.txt`);
  try {
    await downloadStream(track.url, {}, destination.uri);
    const content = await destination.text();
    const cues = track.format.toLowerCase().includes('ttml') ? parseTtml(content) : parseWebVtt(content);
    const text = decodeHtmlEntities(mergeCues(cues)).trim();

    if (text.length < MIN_USABLE_LENGTH) return { status: 'unavailable' };
    return { status: 'found', text, title: decodeHtmlEntities(title) };
  } catch {
    return { status: 'unavailable' };
  }
}
